### ISSUE TITLE
Proxy pass through

### ISSUE THREAD

**Issue by momolog** [conversation/miniproxy#37] opened 2021-04-20 15:07 UTC
I know this is more of a question than an issue, but I cannot achieve a request to a remote server to just be passed through. This is what I write in my rspec:

    MiniProxy.allow_request(method: "GET", url: /heise.de/)

but when I execute

    visit 'https://www.heise.de'

I am getting

```
     Selenium::WebDriver::Error::UnknownError:
       unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
         (Session info: chrome=89.0.4389.128)
```

What am I missing?

**Comment by tiagoamaro** [comment] 2021-04-21 17:42
Hi @momolog,

I wasn't able to reproduce this issue with our setup. We have Webmock and `MiniProxy` disallowing external requests, so here's the step by step of what I tried:

First, I disabled Webmock and `MiniProxy` completely, observing that requests were hanging when trying to access external URLs, as expected with a browser configured with an unresponsive proxy.

Enabling `MiniProxy`, allowing the `heise.de` external request in a system test, using RSpec with headless Chrome 89 and Selenium, I was able to request the website:

![image](https://user-images.githubusercontent.com/1538066/115596088-14171b80-a2ae-11eb-8bf7-94e768b5b224.png)

-----

Could you share an example app reproducing this issue? Thank you!

**Comment by momolog** [comment] 2021-04-24 07:08
@tiagoamaro Thanks for your investigation! I will check my code in the coming week and provide more details.

**Comment by momolog** [comment] 2021-04-26 07:30
Hey @tiagoamaro, I created a little repo to illustrate my problem here: https://github.com/momolog/miniproxy-test
Can you have a look?

**Comment by tiagoamaro** [comment] 2021-04-26 16:42
@momolog, I executed your project following these steps:

- Cloned the project
- Installed Ruby `2.4.2p198`, as the specified `2.3.8` didn't compile on my machine (I guess a single minor version won't affect the setup)
- Using Chrome Version 90.0.4430.85 (Official Build) (64-bit
- Ran `bundle exec rspec spec`:

![miniproxy-working](https://user-images.githubusercontent.com/1538066/116119060-608a9e80-a694-11eb-87e1-4d722a2e88cf.gif)

As you can see the screencast above, everything seems to be working fine on my machine (™), but I wonder if the error you're facing relates to SSL and how your Ruby is compiled (OpenSSL version).

`MiniProxy` uses a self signed certificate that's valid for 100 years (https://github.com/conversation/miniproxy/pull/2), so maybe this is conflicting somehow? Could you test visiting a website that doesn't enforce HTTPS, such as http://example.com with your sample app on your machine?

**Comment by momolog** [comment] 2021-04-26 17:10
@tiagoamaro You are right, `http://example.com` works.
Now I am a bit at loss about how to make MiniProxys certificate work.

**Comment by tiagoamaro** [comment] 2021-04-26 20:17
@momolog , is it possible for you to test in a more modern Ruby? 

We dropped support for Ruby 2.4, also never really testing `MiniProxy` for earlier versions as well (https://github.com/conversation/miniproxy/pull/35).

We'll update the README reporting that `MiniProxy` is supported by Ruby 2.5+, as we have CI running against these versions.

**Comment by tiagoamaro** [comment] 2021-04-27 11:26
@momolog, I'm going to close this issue as it seems to be a local development environment problem.

We are testing `MiniProxy` against Ruby 2.5, 2.6 and 2.7 [1], where we assert allowed pass through requests in our integration tests, making sure it works with HTTP [2] and HTTPS [3].


[1] https://github.com/conversation/miniproxy/blob/1addb3741ea78a85d881b427cdf1105208a3fbba/.travis.yml#L5-L8

[2] https://github.com/conversation/miniproxy/blob/1addb3741ea78a85d881b427cdf1105208a3fbba/spec/integration/stub_requests_spec.rb#L34-L44

[3] https://github.com/conversation/miniproxy/blob/1addb3741ea78a85d881b427cdf1105208a3fbba/spec/integration/stub_requests_spec.rb#L71-L81

**Closed by tiagoamaro** 2021-04-27 11:26 UTC

**Comment by momolog** [comment] 2021-04-27 11:28
Got it.
Thanks a lot for your work and support!
